// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateSessionReq struct {
	User1Id int64 `json:"user1_id"`
	User2Id int64 `json:"user2_id"`
}

type CreateSessionResp struct {
	SessionId int64 `json:"session_id"`
}

type GetMessagesReq struct {
	SessionId int64 `form:"session_id"`
	Cursor    int64 `form:"cursor"`
	Limit     int64 `form:"limit"`
}

type GetMessagesResp struct {
	Messages []Message `json:"messages"`
	HasMore  bool      `json:"has_more"`
}

type Message struct {
	Id         int64  `json:"id"`
	SenderId   int64  `json:"sender_id"`
	ReceiverId int64  `json:"receiver_id"`
	Content    string `json:"content"`
	IsRead     bool   `json:"is_read"`
	SendTime   string `json:"send_time"`
}

type SendMessageReq struct {
	SessionId  int64  `json:"session_id"`
	SenderId   int64  `json:"sender_id"`
	ReceiverId int64  `json:"receiver_id"`
	Content    string `json:"content"`
}

type SendMessageResp struct {
}
