// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Answer struct {
	Id         int64  `json:"id"`
	QuestionId int64  `json:"question_id"`
	UserId     int64  `json:"user_id"`
	Content    string `json:"content"`
	CreateTime string `json:"create_time"`
}

type AnswerReq struct {
	QuestionId int64  `json:"question_id"`
	UserId     int64  `json:"user_id"`
	Content    string `json:"content"`
}

type AnswerResp struct {
	Id int64 `json:"id"`
}

type CreateQuestionReq struct {
	UserId      int64  `json:"user_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type CreateQuestionResp struct {
	Id int64 `json:"id"`
}

type GetAnswersReq struct {
	QuestionId int64 `form:"question_id"`
	Cursor     int64 `form:"cursor"`
	Limit      int64 `form:"limit"`
}

type GetAnswersResp struct {
	Answers []Answer `json:"answers"`
	HasMore bool     `json:"has_more"`
}

type GetQuestionReq struct {
	Id int64 `form:"id"`
}

type GetQuestionResp struct {
	Question Question `json:"question"`
}

type Question struct {
	Id          int64  `json:"id"`
	UserId      int64  `json:"user_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	IsResolved  bool   `json:"is_resolved"`
	CreateTime  string `json:"create_time"`
}
