// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	admin "go_code/zhihu/application/article/api/internal/handler/admin"
	"go_code/zhihu/application/article/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/article/deleted",
				Handler: ArticleDeletedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: ArticleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: ArticleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/publish",
				Handler: PublishHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: ArticleSearchHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/article"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 审核通过
				Method:  http.MethodPost,
				Path:    "/admin/article/approve",
				Handler: admin.ArticleApproveHandler(serverCtx),
			},
			{
				// 待审核列表
				Method:  http.MethodGet,
				Path:    "/admin/article/pending",
				Handler: admin.AdminListHandler(serverCtx),
			},
			{
				// 驳回文章
				Method:  http.MethodPost,
				Path:    "/admin/article/reject",
				Handler: admin.ArticleLRejectHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/article/admin"),
	)
}
