// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: reply.proto

package server

import (
	"context"

	"go_code/zhihu/application/reply/rpc/internal/logic"
	"go_code/zhihu/application/reply/rpc/internal/svc"
	"go_code/zhihu/application/reply/rpc/types/reply"
)

type ReplyServiceServer struct {
	svcCtx *svc.ServiceContext
	reply.UnimplementedReplyServiceServer
}

func NewReplyServiceServer(svcCtx *svc.ServiceContext) *ReplyServiceServer {
	return &ReplyServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ReplyServiceServer) PostReply(ctx context.Context, in *reply.PostReplyRequest) (*reply.PostReplyReply, error) {
	l := logic.NewPostReplyLogic(ctx, s.svcCtx)
	return l.PostReply(in)
}

func (s *ReplyServiceServer) GetReplies(ctx context.Context, in *reply.GetRepliesRequest) (*reply.GetRepliesReply, error) {
	l := logic.NewGetRepliesLogic(ctx, s.svcCtx)
	return l.GetReplies(in)
}
