// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"go_code/zhihu/application/follow/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/fanslist",
				Handler: fansListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: followHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: followListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unfollow",
				Handler: unfollowHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/follow"),
	)
}
