// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"go_code/zhihu/application/follow/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/fans/list",
				Handler: fansListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/follow",
				Handler: followHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/follow/list",
				Handler: followListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/unfollow",
				Handler: unfollowHandler(serverCtx),
			},
		},
	)
}
