// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: article.proto

package server

import (
	"context"

	"go_code/zhihu/application/article/rpc/internal/logic"
	"go_code/zhihu/application/article/rpc/internal/svc"
	"go_code/zhihu/application/article/rpc/types/article"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	article.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) Publish(ctx context.Context, in *article.PublishRequest) (*article.PublishResponse, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *ArticleServer) Articles(ctx context.Context, in *article.ArticlesRequest) (*article.ArticlesResponse, error) {
	l := logic.NewArticlesLogic(ctx, s.svcCtx)
	return l.Articles(in)
}

func (s *ArticleServer) ArticleDelete(ctx context.Context, in *article.ArticleDeleteRequest) (*article.ArticleDeleteResponse, error) {
	l := logic.NewArticleDeleteLogic(ctx, s.svcCtx)
	return l.ArticleDelete(in)
}

func (s *ArticleServer) ArticleDetail(ctx context.Context, in *article.ArticleDetailRequest) (*article.ArticleDetailResponse, error) {
	l := logic.NewArticleDetailLogic(ctx, s.svcCtx)
	return l.ArticleDetail(in)
}
