// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: like.proto

package server

import (
	"context"

	"go_code/zhihu/application/like/rpc/internal/logic"
	"go_code/zhihu/application/like/rpc/internal/svc"
	"go_code/zhihu/application/like/rpc/types/like"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	like.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) Thumbup(ctx context.Context, in *like.ThumbupRequest) (*like.ThumbupResponse, error) {
	l := logic.NewThumbupLogic(ctx, s.svcCtx)
	return l.Thumbup(in)
}

func (s *LikeServer) IsThumbup(ctx context.Context, in *like.IsThumbupRequest) (*like.IsThumbupResponse, error) {
	l := logic.NewIsThumbupLogic(ctx, s.svcCtx)
	return l.IsThumbup(in)
}
