// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: tag.proto

package tag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagName       string                 `protobuf:"bytes,1,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	TagDesc       string                 `protobuf:"bytes,2,opt,name=tag_desc,json=tagDesc,proto3" json:"tag_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTagRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *CreateTagRequest) GetTagDesc() string {
	if x != nil {
		return x.TagDesc
	}
	return ""
}

type CreateTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagReply) Reset() {
	*x = CreateTagReply{}
	mi := &file_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagReply) ProtoMessage() {}

func (x *CreateTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagReply.ProtoReflect.Descriptor instead.
func (*CreateTagReply) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTagReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagRequest) Reset() {
	*x = ListTagRequest{}
	mi := &file_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagRequest) ProtoMessage() {}

func (x *ListTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagRequest.ProtoReflect.Descriptor instead.
func (*ListTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{2}
}

func (x *ListTagRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListTagRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagName       string                 `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	TagDesc       string                 `protobuf:"bytes,3,opt,name=tag_desc,json=tagDesc,proto3" json:"tag_desc,omitempty"`
	CreateTime    string                 `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{3}
}

func (x *Tag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *Tag) GetTagDesc() string {
	if x != nil {
		return x.TagDesc
	}
	return ""
}

func (x *Tag) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type ListTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagReply) Reset() {
	*x = ListTagReply{}
	mi := &file_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagReply) ProtoMessage() {}

func (x *ListTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagReply.ProtoReflect.Descriptor instead.
func (*ListTagReply) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{4}
}

func (x *ListTagReply) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListTagReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type AddTagToResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TagId         int64                  `protobuf:"varint,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTagToResourceRequest) Reset() {
	*x = AddTagToResourceRequest{}
	mi := &file_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTagToResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagToResourceRequest) ProtoMessage() {}

func (x *AddTagToResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagToResourceRequest.ProtoReflect.Descriptor instead.
func (*AddTagToResourceRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{5}
}

func (x *AddTagToResourceRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *AddTagToResourceRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *AddTagToResourceRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *AddTagToResourceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddTagToResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTagToResourceReply) Reset() {
	*x = AddTagToResourceReply{}
	mi := &file_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTagToResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagToResourceReply) ProtoMessage() {}

func (x *AddTagToResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagToResourceReply.ProtoReflect.Descriptor instead.
func (*AddTagToResourceReply) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{6}
}

type GetResourceTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceTagsRequest) Reset() {
	*x = GetResourceTagsRequest{}
	mi := &file_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceTagsRequest) ProtoMessage() {}

func (x *GetResourceTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceTagsRequest.ProtoReflect.Descriptor instead.
func (*GetResourceTagsRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{7}
}

func (x *GetResourceTagsRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *GetResourceTagsRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type GetResourceTagsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceTagsReply) Reset() {
	*x = GetResourceTagsReply{}
	mi := &file_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceTagsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceTagsReply) ProtoMessage() {}

func (x *GetResourceTagsReply) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceTagsReply.ProtoReflect.Descriptor instead.
func (*GetResourceTagsReply) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{8}
}

func (x *GetResourceTagsReply) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagIds        string                 `protobuf:"bytes,1,opt,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsRequest) Reset() {
	*x = GetTagsRequest{}
	mi := &file_tag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsRequest) ProtoMessage() {}

func (x *GetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTagsRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{9}
}

func (x *GetTagsRequest) GetTagIds() string {
	if x != nil {
		return x.TagIds
	}
	return ""
}

type GetTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagNames      []string               `protobuf:"bytes,1,rep,name=tag_names,json=tagNames,proto3" json:"tag_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsResponse) Reset() {
	*x = GetTagsResponse{}
	mi := &file_tag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsResponse) ProtoMessage() {}

func (x *GetTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsResponse.ProtoReflect.Descriptor instead.
func (*GetTagsResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{10}
}

func (x *GetTagsResponse) GetTagNames() []string {
	if x != nil {
		return x.TagNames
	}
	return nil
}

var File_tag_proto protoreflect.FileDescriptor

const file_tag_proto_rawDesc = "" +
	"\n" +
	"\ttag.proto\x12\x03tag\"H\n" +
	"\x10CreateTagRequest\x12\x19\n" +
	"\btag_name\x18\x01 \x01(\tR\atagName\x12\x19\n" +
	"\btag_desc\x18\x02 \x01(\tR\atagDesc\" \n" +
	"\x0eCreateTagReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x0eListTagRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"l\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\btag_name\x18\x02 \x01(\tR\atagName\x12\x19\n" +
	"\btag_desc\x18\x03 \x01(\tR\atagDesc\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\tR\n" +
	"createTime\"G\n" +
	"\fListTagReply\x12\x1c\n" +
	"\x04tags\x18\x01 \x03(\v2\b.tag.TagR\x04tags\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"}\n" +
	"\x17AddTagToResourceRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x15\n" +
	"\x06tag_id\x18\x03 \x01(\x03R\x05tagId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"\x17\n" +
	"\x15AddTagToResourceReply\"L\n" +
	"\x16GetResourceTagsRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\"4\n" +
	"\x14GetResourceTagsReply\x12\x1c\n" +
	"\x04tags\x18\x01 \x03(\v2\b.tag.TagR\x04tags\")\n" +
	"\x0eGetTagsRequest\x12\x17\n" +
	"\atag_ids\x18\x01 \x01(\tR\x06tagIds\".\n" +
	"\x0fGetTagsResponse\x12\x1b\n" +
	"\ttag_names\x18\x01 \x03(\tR\btagNames2\xc7\x02\n" +
	"\n" +
	"TagService\x127\n" +
	"\tCreateTag\x12\x15.tag.CreateTagRequest\x1a\x13.tag.CreateTagReply\x121\n" +
	"\aListTag\x12\x13.tag.ListTagRequest\x1a\x11.tag.ListTagReply\x12L\n" +
	"\x10AddTagToResource\x12\x1c.tag.AddTagToResourceRequest\x1a\x1a.tag.AddTagToResourceReply\x12I\n" +
	"\x0fGetResourceTags\x12\x1b.tag.GetResourceTagsRequest\x1a\x19.tag.GetResourceTagsReply\x124\n" +
	"\aGetTags\x12\x13.tag.GetTagsRequest\x1a\x14.tag.GetTagsResponseB\aZ\x05./tagb\x06proto3"

var (
	file_tag_proto_rawDescOnce sync.Once
	file_tag_proto_rawDescData []byte
)

func file_tag_proto_rawDescGZIP() []byte {
	file_tag_proto_rawDescOnce.Do(func() {
		file_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)))
	})
	return file_tag_proto_rawDescData
}

var file_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tag_proto_goTypes = []any{
	(*CreateTagRequest)(nil),        // 0: tag.CreateTagRequest
	(*CreateTagReply)(nil),          // 1: tag.CreateTagReply
	(*ListTagRequest)(nil),          // 2: tag.ListTagRequest
	(*Tag)(nil),                     // 3: tag.Tag
	(*ListTagReply)(nil),            // 4: tag.ListTagReply
	(*AddTagToResourceRequest)(nil), // 5: tag.AddTagToResourceRequest
	(*AddTagToResourceReply)(nil),   // 6: tag.AddTagToResourceReply
	(*GetResourceTagsRequest)(nil),  // 7: tag.GetResourceTagsRequest
	(*GetResourceTagsReply)(nil),    // 8: tag.GetResourceTagsReply
	(*GetTagsRequest)(nil),          // 9: tag.GetTagsRequest
	(*GetTagsResponse)(nil),         // 10: tag.GetTagsResponse
}
var file_tag_proto_depIdxs = []int32{
	3,  // 0: tag.ListTagReply.tags:type_name -> tag.Tag
	3,  // 1: tag.GetResourceTagsReply.tags:type_name -> tag.Tag
	0,  // 2: tag.TagService.CreateTag:input_type -> tag.CreateTagRequest
	2,  // 3: tag.TagService.ListTag:input_type -> tag.ListTagRequest
	5,  // 4: tag.TagService.AddTagToResource:input_type -> tag.AddTagToResourceRequest
	7,  // 5: tag.TagService.GetResourceTags:input_type -> tag.GetResourceTagsRequest
	9,  // 6: tag.TagService.GetTags:input_type -> tag.GetTagsRequest
	1,  // 7: tag.TagService.CreateTag:output_type -> tag.CreateTagReply
	4,  // 8: tag.TagService.ListTag:output_type -> tag.ListTagReply
	6,  // 9: tag.TagService.AddTagToResource:output_type -> tag.AddTagToResourceReply
	8,  // 10: tag.TagService.GetResourceTags:output_type -> tag.GetResourceTagsReply
	10, // 11: tag.TagService.GetTags:output_type -> tag.GetTagsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_tag_proto_init() }
func file_tag_proto_init() {
	if File_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_proto_goTypes,
		DependencyIndexes: file_tag_proto_depIdxs,
		MessageInfos:      file_tag_proto_msgTypes,
	}.Build()
	File_tag_proto = out.File
	file_tag_proto_goTypes = nil
	file_tag_proto_depIdxs = nil
}
