// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type IsThumbupReq struct {
	BizId    string `form:"biz_id"`
	TargetId int64  `form:"target_id"`
	UserId   int64  `form:"user_id"`
}

type IsThumbupResp struct {
	UserThumbups map[int64]UserThumbup `json:"user_thumbups"`
}

type ThumbupReq struct {
	BizId    string `json:"biz_id"`
	ObjId    int64  `json:"obj_id"`
	UserId   int64  `json:"user_id"`
	LikeType int32  `json:"like_type"` // 1=点赞，2=点踩
}

type ThumbupResp struct {
	BizId      string `json:"biz_id"`
	ObjId      int64  `json:"obj_id"`
	LikeNum    int64  `json:"like_num"`
	DislikeNum int64  `json:"dislike_num"`
}

type UserThumbup struct {
	UserId      int64 `json:"user_id"`
	ThumbupTime int64 `json:"thumbup_time"`
	LikeType    int32 `json:"like_type"`
}
