// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"go_code/zhihu/application/chat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/chat/message/send",
				Handler: sendMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/messages/list",
				Handler: getMessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/chat/session/create",
				Handler: createSessionHandler(serverCtx),
			},
		},
	)
}
