// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type FansItem struct {
	UserId      int64 `json:"user_id"`
	FansUserId  int64 `json:"fans_user_id"`
	FollowCount int64 `json:"follow_count"`
	FansCount   int64 `json:"fans_count"`
	CreateTime  int64 `json:"create_time"`
}

type FansListReq struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type FansListResp struct {
	Items  []FansItem `json:"items"`
	Cursor int64      `json:"cursor"`
	IsEnd  bool       `json:"is_end"`
}

type FollowItem struct {
	Id             int64 `json:"id"`
	FollowedUserId int64 `json:"followed_user_id"`
	FansCount      int64 `json:"fans_count"`
	CreateTime     int64 `json:"create_time"`
}

type FollowListReq struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type FollowListResp struct {
	Items  []FollowItem `json:"items"`
	Cursor int64        `json:"cursor"`
	IsEnd  bool         `json:"is_end"`
}

type FollowReq struct {
	FollowedUserId int64 `json:"followed_user_id"` // 被关注者
}

type FollowResp struct {
}

type UnFollowReq struct {
	FollowedUserId int64 `json:"followed_user_id"`
}

type UnFollowResp struct {
}
