// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: reply.proto

package reply

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 评论写入
type PostReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ReplyUserId   int64                  `protobuf:"varint,3,opt,name=reply_user_id,json=replyUserId,proto3" json:"reply_user_id,omitempty"`
	BeReplyUserId int64                  `protobuf:"varint,4,opt,name=be_reply_user_id,json=beReplyUserId,proto3" json:"be_reply_user_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostReplyRequest) Reset() {
	*x = PostReplyRequest{}
	mi := &file_reply_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReplyRequest) ProtoMessage() {}

func (x *PostReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReplyRequest.ProtoReflect.Descriptor instead.
func (*PostReplyRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{0}
}

func (x *PostReplyRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *PostReplyRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *PostReplyRequest) GetReplyUserId() int64 {
	if x != nil {
		return x.ReplyUserId
	}
	return 0
}

func (x *PostReplyRequest) GetBeReplyUserId() int64 {
	if x != nil {
		return x.BeReplyUserId
	}
	return 0
}

func (x *PostReplyRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *PostReplyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PostReplyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostReplyReply) Reset() {
	*x = PostReplyReply{}
	mi := &file_reply_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReplyReply) ProtoMessage() {}

func (x *PostReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReplyReply.ProtoReflect.Descriptor instead.
func (*PostReplyReply) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{1}
}

func (x *PostReplyReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 评论列表（游标分页）
type GetRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesRequest) Reset() {
	*x = GetRepliesRequest{}
	mi := &file_reply_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesRequest) ProtoMessage() {}

func (x *GetRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesRequest.ProtoReflect.Descriptor instead.
func (*GetRepliesRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{2}
}

func (x *GetRepliesRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *GetRepliesRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *GetRepliesRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetRepliesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BizId         string                 `protobuf:"bytes,2,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ReplyUserId   int64                  `protobuf:"varint,4,opt,name=reply_user_id,json=replyUserId,proto3" json:"reply_user_id,omitempty"`
	BeReplyUserId int64                  `protobuf:"varint,5,opt,name=be_reply_user_id,json=beReplyUserId,proto3" json:"be_reply_user_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	LikeNum       int64                  `protobuf:"varint,8,opt,name=like_num,json=likeNum,proto3" json:"like_num,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,9,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreateTime    string                 `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_reply_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{3}
}

func (x *Reply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Reply) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *Reply) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Reply) GetReplyUserId() int64 {
	if x != nil {
		return x.ReplyUserId
	}
	return 0
}

func (x *Reply) GetBeReplyUserId() int64 {
	if x != nil {
		return x.BeReplyUserId
	}
	return 0
}

func (x *Reply) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Reply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Reply) GetLikeNum() int64 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *Reply) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Reply) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type GetRepliesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*Reply               `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesReply) Reset() {
	*x = GetRepliesReply{}
	mi := &file_reply_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesReply) ProtoMessage() {}

func (x *GetRepliesReply) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesReply.ProtoReflect.Descriptor instead.
func (*GetRepliesReply) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{4}
}

func (x *GetRepliesReply) GetReplies() []*Reply {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *GetRepliesReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_reply_proto protoreflect.FileDescriptor

const file_reply_proto_rawDesc = "" +
	"\n" +
	"\vreply.proto\x12\x05reply\"\xca\x01\n" +
	"\x10PostReplyRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\"\n" +
	"\rreply_user_id\x18\x03 \x01(\x03R\vreplyUserId\x12'\n" +
	"\x10be_reply_user_id\x18\x04 \x01(\x03R\rbeReplyUserId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\" \n" +
	"\x0ePostReplyReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"u\n" +
	"\x11GetRepliesRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"\xaa\x02\n" +
	"\x05Reply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06biz_id\x18\x02 \x01(\tR\x05bizId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\"\n" +
	"\rreply_user_id\x18\x04 \x01(\x03R\vreplyUserId\x12'\n" +
	"\x10be_reply_user_id\x18\x05 \x01(\x03R\rbeReplyUserId\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x19\n" +
	"\blike_num\x18\b \x01(\x03R\alikeNum\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\t \x01(\bR\tisDeleted\x12\x1f\n" +
	"\vcreate_time\x18\n" +
	" \x01(\tR\n" +
	"createTime\"T\n" +
	"\x0fGetRepliesReply\x12&\n" +
	"\areplies\x18\x01 \x03(\v2\f.reply.ReplyR\areplies\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore2\x8b\x01\n" +
	"\fReplyService\x12;\n" +
	"\tPostReply\x12\x17.reply.PostReplyRequest\x1a\x15.reply.PostReplyReply\x12>\n" +
	"\n" +
	"GetReplies\x12\x18.reply.GetRepliesRequest\x1a\x16.reply.GetRepliesReplyB\tZ\a./replyb\x06proto3"

var (
	file_reply_proto_rawDescOnce sync.Once
	file_reply_proto_rawDescData []byte
)

func file_reply_proto_rawDescGZIP() []byte {
	file_reply_proto_rawDescOnce.Do(func() {
		file_reply_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reply_proto_rawDesc), len(file_reply_proto_rawDesc)))
	})
	return file_reply_proto_rawDescData
}

var file_reply_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_reply_proto_goTypes = []any{
	(*PostReplyRequest)(nil),  // 0: reply.PostReplyRequest
	(*PostReplyReply)(nil),    // 1: reply.PostReplyReply
	(*GetRepliesRequest)(nil), // 2: reply.GetRepliesRequest
	(*Reply)(nil),             // 3: reply.Reply
	(*GetRepliesReply)(nil),   // 4: reply.GetRepliesReply
}
var file_reply_proto_depIdxs = []int32{
	3, // 0: reply.GetRepliesReply.replies:type_name -> reply.Reply
	0, // 1: reply.ReplyService.PostReply:input_type -> reply.PostReplyRequest
	2, // 2: reply.ReplyService.GetReplies:input_type -> reply.GetRepliesRequest
	1, // 3: reply.ReplyService.PostReply:output_type -> reply.PostReplyReply
	4, // 4: reply.ReplyService.GetReplies:output_type -> reply.GetRepliesReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reply_proto_init() }
func file_reply_proto_init() {
	if File_reply_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reply_proto_rawDesc), len(file_reply_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reply_proto_goTypes,
		DependencyIndexes: file_reply_proto_depIdxs,
		MessageInfos:      file_reply_proto_msgTypes,
	}.Build()
	File_reply_proto = out.File
	file_reply_proto_goTypes = nil
	file_reply_proto_depIdxs = nil
}
