// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AddTagToResourceReq struct {
	BizId    string `json:"biz_id"`
	TargetId int64  `json:"target_id"`
	TagId    int64  `json:"tag_id"`
	UserId   int64  `json:"user_id"`
}

type AddTagToResourceResp struct {
}

type CreateTagReq struct {
	TagName string `json:"tag_name"`
	TagDesc string `json:"tag_desc"`
}

type CreateTagResp struct {
	Id int64 `json:"id"`
}

type GetResourceTagsReq struct {
	BizId    string `form:"biz_id"`
	TargetId int64  `form:"target_id"`
}

type GetResourceTagsResp struct {
	Tags []Tag `json:"tags"`
}

type ListTagReq struct {
	Cursor int64 `form:"cursor"`
	Limit  int64 `form:"limit"`
}

type ListTagResp struct {
	Tags    []Tag `json:"tags"`
	HasMore bool  `json:"has_more"`
}

type Tag struct {
	Id         int64  `json:"id"`
	TagName    string `json:"tag_name"`
	TagDesc    string `json:"tag_desc"`
	CreateTime string `json:"create_time"`
}
