// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: qa.proto

package qa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_qa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQuestionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateQuestionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateQuestionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateQuestionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionReply) Reset() {
	*x = CreateQuestionReply{}
	mi := &file_qa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionReply) ProtoMessage() {}

func (x *CreateQuestionReply) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionReply.ProtoReflect.Descriptor instead.
func (*CreateQuestionReply) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQuestionReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_qa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsResolved    bool                   `protobuf:"varint,5,opt,name=is_resolved,json=isResolved,proto3" json:"is_resolved,omitempty"`
	CreateTime    string                 `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_qa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{3}
}

func (x *Question) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Question) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Question) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Question) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Question) GetIsResolved() bool {
	if x != nil {
		return x.IsResolved
	}
	return false
}

func (x *Question) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type GetQuestionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionReply) Reset() {
	*x = GetQuestionReply{}
	mi := &file_qa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionReply) ProtoMessage() {}

func (x *GetQuestionReply) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionReply.ProtoReflect.Descriptor instead.
func (*GetQuestionReply) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{4}
}

func (x *GetQuestionReply) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type AnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	mi := &file_qa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{5}
}

func (x *AnswerRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AnswerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AnswerRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AnswerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerReply) Reset() {
	*x = AnswerReply{}
	mi := &file_qa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerReply) ProtoMessage() {}

func (x *AnswerReply) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerReply.ProtoReflect.Descriptor instead.
func (*AnswerReply) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{6}
}

func (x *AnswerReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnswersRequest) Reset() {
	*x = GetAnswersRequest{}
	mi := &file_qa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswersRequest) ProtoMessage() {}

func (x *GetAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswersRequest.ProtoReflect.Descriptor instead.
func (*GetAnswersRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnswersRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *GetAnswersRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetAnswersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionId    int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime    string                 `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_qa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{8}
}

func (x *Answer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Answer) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *Answer) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Answer) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Answer) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type GetAnswersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []*Answer              `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnswersReply) Reset() {
	*x = GetAnswersReply{}
	mi := &file_qa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswersReply) ProtoMessage() {}

func (x *GetAnswersReply) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswersReply.ProtoReflect.Descriptor instead.
func (*GetAnswersReply) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{9}
}

func (x *GetAnswersReply) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *GetAnswersReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_qa_proto protoreflect.FileDescriptor

const file_qa_proto_rawDesc = "" +
	"\n" +
	"\bqa.proto\x12\x02qa\"h\n" +
	"\x15CreateQuestionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"%\n" +
	"\x13CreateQuestionReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12GetQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xad\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vis_resolved\x18\x05 \x01(\bR\n" +
	"isResolved\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\tR\n" +
	"createTime\"<\n" +
	"\x10GetQuestionReply\x12(\n" +
	"\bquestion\x18\x01 \x01(\v2\f.qa.QuestionR\bquestion\"c\n" +
	"\rAnswerRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x1d\n" +
	"\vAnswerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"b\n" +
	"\x11GetAnswersRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"\x8d\x01\n" +
	"\x06Answer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\tR\n" +
	"createTime\"R\n" +
	"\x0fGetAnswersReply\x12$\n" +
	"\aanswers\x18\x01 \x03(\v2\n" +
	".qa.AnswerR\aanswers\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore2\xfe\x01\n" +
	"\tQaService\x12D\n" +
	"\x0eCreateQuestion\x12\x19.qa.CreateQuestionRequest\x1a\x17.qa.CreateQuestionReply\x12;\n" +
	"\vGetQuestion\x12\x16.qa.GetQuestionRequest\x1a\x14.qa.GetQuestionReply\x124\n" +
	"\x0eAnswerQuestion\x12\x11.qa.AnswerRequest\x1a\x0f.qa.AnswerReply\x128\n" +
	"\n" +
	"GetAnswers\x12\x15.qa.GetAnswersRequest\x1a\x13.qa.GetAnswersReplyB\x06Z\x04./qab\x06proto3"

var (
	file_qa_proto_rawDescOnce sync.Once
	file_qa_proto_rawDescData []byte
)

func file_qa_proto_rawDescGZIP() []byte {
	file_qa_proto_rawDescOnce.Do(func() {
		file_qa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qa_proto_rawDesc), len(file_qa_proto_rawDesc)))
	})
	return file_qa_proto_rawDescData
}

var file_qa_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_qa_proto_goTypes = []any{
	(*CreateQuestionRequest)(nil), // 0: qa.CreateQuestionRequest
	(*CreateQuestionReply)(nil),   // 1: qa.CreateQuestionReply
	(*GetQuestionRequest)(nil),    // 2: qa.GetQuestionRequest
	(*Question)(nil),              // 3: qa.Question
	(*GetQuestionReply)(nil),      // 4: qa.GetQuestionReply
	(*AnswerRequest)(nil),         // 5: qa.AnswerRequest
	(*AnswerReply)(nil),           // 6: qa.AnswerReply
	(*GetAnswersRequest)(nil),     // 7: qa.GetAnswersRequest
	(*Answer)(nil),                // 8: qa.Answer
	(*GetAnswersReply)(nil),       // 9: qa.GetAnswersReply
}
var file_qa_proto_depIdxs = []int32{
	3, // 0: qa.GetQuestionReply.question:type_name -> qa.Question
	8, // 1: qa.GetAnswersReply.answers:type_name -> qa.Answer
	0, // 2: qa.QaService.CreateQuestion:input_type -> qa.CreateQuestionRequest
	2, // 3: qa.QaService.GetQuestion:input_type -> qa.GetQuestionRequest
	5, // 4: qa.QaService.AnswerQuestion:input_type -> qa.AnswerRequest
	7, // 5: qa.QaService.GetAnswers:input_type -> qa.GetAnswersRequest
	1, // 6: qa.QaService.CreateQuestion:output_type -> qa.CreateQuestionReply
	4, // 7: qa.QaService.GetQuestion:output_type -> qa.GetQuestionReply
	6, // 8: qa.QaService.AnswerQuestion:output_type -> qa.AnswerReply
	9, // 9: qa.QaService.GetAnswers:output_type -> qa.GetAnswersReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_qa_proto_init() }
func file_qa_proto_init() {
	if File_qa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qa_proto_rawDesc), len(file_qa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qa_proto_goTypes,
		DependencyIndexes: file_qa_proto_depIdxs,
		MessageInfos:      file_qa_proto_msgTypes,
	}.Build()
	File_qa_proto = out.File
	file_qa_proto_goTypes = nil
	file_qa_proto_depIdxs = nil
}
