// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AdminListRequest struct {
	Cursor    int64 `form:"cursor"` //游标，发布时间
	ArticleId int64 `form:"article_id"`
	PageSize  int64 `form:"page_size"`
	Status    int64 `form:"status,optional"` //筛选状态：0=待审核, 1=驳回
}

type AdminListResponse struct {
	Articles  []PendingArticleItem `json:"articles"`
	Cursor    int64                `json:"cursor"`
	ArticleId int64                `json:"article_id"`
	IsEnd     bool                 `json:"is_end"`
}

type ArticleApproveRequest struct {
	ArticleId int64 `json:"article_id"` // 待审核的文章 ID
}

type ArticleApproveResponse struct {
}

type ArticleLRejectRequest struct {
	ArticleId int64  `json:"article_id"` // 被驳回文章 ID
	Reason    string `json:"reason"`     //驳回原因
}

type ArticleLRejectResponse struct {
}
