// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type PublishRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type PublishResponse struct {
	ArticleId int64 `json:"article_id"`
}
