// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"go_code/zhihu/application/qa/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/answer",
				Handler: answerQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/answer/list",
				Handler: getAnswersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/question/create",
				Handler: createQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/question/detail",
				Handler: getQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/question/list",
				Handler: getQuestionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/qa"),
	)
}
