// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likeFieldNames          = builder.RawFieldNames(&Like{})
	likeRows                = strings.Join(likeFieldNames, ",")
	likeRowsExpectAutoSet   = strings.Join(stringx.Remove(likeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	likeRowsWithPlaceHolder = strings.Join(stringx.Remove(likeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBeyondLikeLikeIdPrefix = "cache:beyondLike:like:id:"
)

type (
	likeModel interface {
		Insert(ctx context.Context, data *Like) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Like, error)
		Update(ctx context.Context, data *Like) error
		Delete(ctx context.Context, id uint64) error
		Exists(bizId string, targetId, userId int64) (bool, error)
		FindByUnique(ctx context.Context, bizId string, targetId, userId int64) (*Like, error)
		Upsert(ctx context.Context, l *Like) error
	}

	defaultLikeModel struct {
		sqlc.CachedConn
		table string
	}

	Like struct {
		Id         uint64    `db:"id"`          // 主键ID
		BizId      string    `db:"biz_id"`      // 业务ID
		TargetId   uint64    `db:"target_id"`   // 点赞目标id
		UserId     uint64    `db:"user_id"`     // 用户ID
		Type       int64     `db:"type"`        // 类型 0:点赞 1:点踩
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 最后修改时间
		Deleted    int64     `db:"deleted"`     // 是否已撤销（0=有效，1=取消）
	}
)

func newLikeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLikeModel {
	return &defaultLikeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`like`",
	}
}

func (m *defaultLikeModel) Delete(ctx context.Context, id uint64) error {
	beyondLikeLikeIdKey := fmt.Sprintf("%s%v", cacheBeyondLikeLikeIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, beyondLikeLikeIdKey)
	return err
}

func (m *defaultLikeModel) FindOne(ctx context.Context, id uint64) (*Like, error) {
	beyondLikeLikeIdKey := fmt.Sprintf("%s%v", cacheBeyondLikeLikeIdPrefix, id)
	var resp Like
	err := m.QueryRowCtx(ctx, &resp, beyondLikeLikeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", likeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) Insert(ctx context.Context, data *Like) (sql.Result, error) {
	beyondLikeLikeIdKey := fmt.Sprintf("%s%v", cacheBeyondLikeLikeIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, likeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BizId, data.TargetId, data.UserId, data.Type, data.Deleted)
	}, beyondLikeLikeIdKey)
	return ret, err
}

func (m *defaultLikeModel) Update(ctx context.Context, data *Like) error {
	beyondLikeLikeIdKey := fmt.Sprintf("%s%v", cacheBeyondLikeLikeIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, likeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.BizId, data.TargetId, data.UserId, data.Type, data.Deleted, data.Id)
	}, beyondLikeLikeIdKey)
	return err
}

func (m *defaultLikeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBeyondLikeLikeIdPrefix, primary)
}

func (m *defaultLikeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", likeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLikeModel) tableName() string {
	return m.table
}
