// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likeCountFieldNames          = builder.RawFieldNames(&LikeCount{})
	likeCountRows                = strings.Join(likeCountFieldNames, ",")
	likeCountRowsExpectAutoSet   = strings.Join(stringx.Remove(likeCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	likeCountRowsWithPlaceHolder = strings.Join(stringx.Remove(likeCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBeyondLikeLikeCountIdPrefix = "cache:beyondLike:likeCount:id:"
)

type (
	likeCountModel interface {
		Insert(ctx context.Context, data *LikeCount) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*LikeCount, error)
		Update(ctx context.Context, data *LikeCount) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultLikeCountModel struct {
		sqlc.CachedConn
		table string
	}

	LikeCount struct {
		Id         uint64    `db:"id"`          // 主键ID
		BizId      string    `db:"biz_id"`      // 业务ID
		TargetId   uint64    `db:"target_id"`   // 内容id
		LikeNum    int64     `db:"like_num"`    // 点赞数
		DislikeNum int64     `db:"dislike_num"` // 点踩数
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 最后修改时间
	}
)

func newLikeCountModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLikeCountModel {
	return &defaultLikeCountModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`like_count`",
	}
}

func (m *defaultLikeCountModel) Delete(ctx context.Context, id uint64) error {
	beyondLikeLikeCountIdKey := fmt.Sprintf("%s%v", cacheBeyondLikeLikeCountIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, beyondLikeLikeCountIdKey)
	return err
}

func (m *defaultLikeCountModel) FindOne(ctx context.Context, id uint64) (*LikeCount, error) {
	beyondLikeLikeCountIdKey := fmt.Sprintf("%s%v", cacheBeyondLikeLikeCountIdPrefix, id)
	var resp LikeCount
	err := m.QueryRowCtx(ctx, &resp, beyondLikeLikeCountIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", likeCountRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikeCountModel) Insert(ctx context.Context, data *LikeCount) (sql.Result, error) {
	beyondLikeLikeCountIdKey := fmt.Sprintf("%s%v", cacheBeyondLikeLikeCountIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, likeCountRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BizId, data.TargetId, data.LikeNum, data.DislikeNum)
	}, beyondLikeLikeCountIdKey)
	return ret, err
}

func (m *defaultLikeCountModel) Update(ctx context.Context, data *LikeCount) error {
	beyondLikeLikeCountIdKey := fmt.Sprintf("%s%v", cacheBeyondLikeLikeCountIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, likeCountRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.BizId, data.TargetId, data.LikeNum, data.DislikeNum, data.Id)
	}, beyondLikeLikeCountIdKey)
	return err
}

func (m *defaultLikeCountModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBeyondLikeLikeCountIdPrefix, primary)
}

func (m *defaultLikeCountModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", likeCountRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLikeCountModel) tableName() string {
	return m.table
}
