// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: article.proto

package articleclient

import (
	"context"

	"go_code/zhihu/application/article/rpc/types/article"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PublishRequest  = article.PublishRequest
	PublishResponse = article.PublishResponse

	Article interface {
		Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	}

	defaultArticle struct {
		cli zrpc.Client
	}
)

func NewArticle(cli zrpc.Client) Article {
	return &defaultArticle{
		cli: cli,
	}
}

func (m *defaultArticle) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	client := article.NewArticleClient(m.cli.Conn())
	return client.Publish(ctx, in, opts...)
}
