// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chatSessionFieldNames          = builder.RawFieldNames(&ChatSession{})
	chatSessionRows                = strings.Join(chatSessionFieldNames, ",")
	chatSessionRowsExpectAutoSet   = strings.Join(stringx.Remove(chatSessionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	chatSessionRowsWithPlaceHolder = strings.Join(stringx.Remove(chatSessionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	chatSessionModel interface {
		Insert(ctx context.Context, data *ChatSession) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ChatSession, error)
		FindOneByUser1IdUser2Id(ctx context.Context, user1Id uint64, user2Id uint64) (*ChatSession, error)
		Update(ctx context.Context, data *ChatSession) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultChatSessionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChatSession struct {
		Id         uint64    `db:"id"`          // 会话ID
		User1Id    uint64    `db:"user1_id"`    // 用户1
		User2Id    uint64    `db:"user2_id"`    // 用户2
		CreateTime time.Time `db:"create_time"` // 创建时间
	}
)

func newChatSessionModel(conn sqlx.SqlConn) *defaultChatSessionModel {
	return &defaultChatSessionModel{
		conn:  conn,
		table: "`chat_session`",
	}
}

func (m *defaultChatSessionModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChatSessionModel) FindOne(ctx context.Context, id uint64) (*ChatSession, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatSessionRows, m.table)
	var resp ChatSession
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatSessionModel) FindOneByUser1IdUser2Id(ctx context.Context, user1Id uint64, user2Id uint64) (*ChatSession, error) {
	var resp ChatSession
	query := fmt.Sprintf("select %s from %s where `user1_id` = ? and `user2_id` = ? limit 1", chatSessionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, user1Id, user2Id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatSessionModel) Insert(ctx context.Context, data *ChatSession) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, chatSessionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.User1Id, data.User2Id)
	return ret, err
}

func (m *defaultChatSessionModel) Update(ctx context.Context, newData *ChatSession) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatSessionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.User1Id, newData.User2Id, newData.Id)
	return err
}

func (m *defaultChatSessionModel) tableName() string {
	return m.table
}
