// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	questionFieldNames          = builder.RawFieldNames(&Question{})
	questionRows                = strings.Join(questionFieldNames, ",")
	questionRowsExpectAutoSet   = strings.Join(stringx.Remove(questionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	questionRowsWithPlaceHolder = strings.Join(stringx.Remove(questionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	questionModel interface {
		Insert(ctx context.Context, data *Question) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Question, error)
		Update(ctx context.Context, data *Question) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultQuestionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Question struct {
		Id          uint64    `db:"id"`          // 问题ID
		UserId      uint64    `db:"user_id"`     // 提问者
		Title       string    `db:"title"`       // 问题标题
		Description string    `db:"description"` // 问题描述
		IsResolved  bool      `db:"is_resolved"` // 是否已解决
		CreateTime  time.Time `db:"create_time"` // 创建时间
		UpdateTime  time.Time `db:"update_time"` // 更新时间
	}
)

func newQuestionModel(conn sqlx.SqlConn) *defaultQuestionModel {
	return &defaultQuestionModel{
		conn:  conn,
		table: "`question`",
	}
}

func (m *defaultQuestionModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultQuestionModel) FindOne(ctx context.Context, id uint64) (*Question, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", questionRows, m.table)
	var resp Question
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultQuestionModel) Insert(ctx context.Context, data *Question) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, questionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Description, data.IsResolved)
	return ret, err
}

func (m *defaultQuestionModel) Update(ctx context.Context, data *Question) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, questionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Description, data.IsResolved, data.Id)
	return err
}

func (m *defaultQuestionModel) tableName() string {
	return m.table
}
