// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GetMessagesReq struct {
	ReceiverId int64 `form:"receiver_id"`
	Cursor     int64 `form:"cursor"`
	Limit      int64 `form:"limit"`
}

type GetMessagesResp struct {
	Messages []Message `json:"messages"`
	HasMore  bool      `json:"has_more"`
}

type MarkAsReadReq struct {
	Id int64 `json:"id"`
}

type MarkAsReadResp struct {
}

type Message struct {
	Id         int64  `json:"id"`
	Type       int32  `json:"type"`
	BizId      string `json:"biz_id"`
	TargetId   int64  `json:"target_id"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	IsRead     bool   `json:"is_read"`
	CreateTime string `json:"create_time"`
}

type SendMessageReq struct {
	Type       int32  `json:"type"`        // 类型，如 0系统消息、1点赞、2评论
	BizId      string `json:"biz_id"`      // 业务ID
	TargetId   int64  `json:"target_id"`   // 内容ID
	ReceiverId int64  `json:"receiver_id"` // 接收者
	Title      string `json:"title"`
	Content    string `json:"content"`
}

type SendMessageResp struct {
}
